version: "3"
services:
  backend:
    build: ./api
    image: nattapat34/fast-food-api:lastest
    ports:
      - "4000:4000"
    networks:
      - svv
    container_name: api_container
  frontend:
    build: ./app
    image: nattapat34/fast-food-app:lastest
    ports:
      - "3000:3000"
    container_name: app_container
    networks:
      - svv
  webserver:
      image: nginx
      container_name: webserver
      build:
        context: .
        dockerfile: ./Dockerfile
      ports:
        - 8081:8081
      restart: always
      networks:
        - svv
      depends_on:
        - frontend
        - backend
networks:
  svv:
    driver: bridge