version: "3"
services:
  backend:
    build: ./api
    image: nattapat34/fast-food-api:lastest
    ports:
      - "4000:3001"
    container_name: api_container
  frontend:
    build: ./app
    image: nattapat34/fast-food-app:lastest
    ports:
      - "3000:3000"
    container_name: app_container
  nginx:
    image: nginx:latest
    container_name: nginx_container
    restart: always
    ports:
      - "81:81"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend