version: "3"
services:
  backend:
    build: ./api
    image: nattapat34/fast-food-backend:lastest
    ports:
      - "4000:3000"
    container_name: fast-api_container
  frontend:
    build: ./app
    image: nattapat34/fast-food-frontend:latest
    ports:
      - "3000:3000"
    container_name: frontend_container
